from pydantic import BaseModel, EmailStr, Field

class User(BaseModel):
  """
  SQL used for creating 'WebUsers' table

  ```
  CREATE TABLE WebUser (
    UserID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50),
    Email VARCHAR(100),
    HashedPassword VARCHAR(255),
    Salt VARCHAR(10)
  );
  ```
  """
  email: EmailStr
  first_name: str
  last_name: str
  hashed_password: str
  salt: str

class CreateUser(BaseModel):
  """
  JSON type received from the frontend for creating new user
  """
  first_name: str = Field(alias="firstName")
  last_name: str = Field(alias="lastName")
  email: str
  password: str

  model_config = {
    "populate_by_name": True # can use python's field or alias
  }

class LoginUser(BaseModel):
  """
  JSON type received from the frontend for logging in user
  """
  email: str
  password: str
