from pydantic import BaseModel, EmailStr

class User(BaseModel):
  """
  SQL used for creating 'WebUsers' table

  ```
  CREATE TABLE WebUser (
    UserID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50),
    Email VARCHAR(100),
    HashedPassword VARCHAR(255),
    Salt VARCHAR(10)
  );
  ```
  """
  email: EmailStr
  first_name: str
  last_name: str
  hashed_password: str
  salt: str
